version: "3.7"

name: nodejs-siege

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    env_file: .env

  node-app:
    build: .
    env_file: .env
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    restart: always

networks:
  default:
    driver: bridge
